
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

comment.avatar: /images/hanj.jpg

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql